# Generated by Django 3.1.7 on 2021-07-29 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('hourly_charge_currency', djmoney.models.fields.CurrencyField(choices=[('UGX', 'UGX /=')], default=None, editable=False, max_length=3, null=True)),
                ('hourly_charge', djmoney.models.fields.MoneyField(decimal_places=3, max_digits=19, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employer')),
            ],
            options={
                'verbose_name': 'Add employer',
                'verbose_name_plural': 'Add employers',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
