# Generated by Django 3.1.7 on 2021-07-29 10:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addemployer',
            options={'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
        migrations.AddField(
            model_name='addemployer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addemployer',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addemployer',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='addemployer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addemployer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='addemployer',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='addemployer',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addemployer',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addemployer',
            name='hourly_charge',
            field=djmoney.models.fields.MoneyField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addemployer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employer'),
        ),
        migrations.AlterModelTable(
            name='addemployer',
            table=None,
        ),
    ]
