# Generated by Django 3.1.7 on 2021-07-29 11:15

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210729_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployer',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Time should be expressed in 24 hours eg 17:00:00 if you want to achieve pm, default is am', null=True),
        ),
        migrations.AlterField(
            model_name='addemployer',
            name='hourly_charge',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
