# Generated by Django 3.1.7 on 2021-07-30 10:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210729_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployer',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='What is this worker supposed to do in a day', null=True),
        ),
    ]
