# Generated by Django 3.1.7 on 2021-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210730_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployer',
            name='job_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
